In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('energydata_complete.csv')


In [3]:
df.head()

Unnamed: 0                 date  Appliances  lights     T1       RH_1  \
0           0  2016-01-11 17:00:00          60      30  19.89  47.596667   
1           1  2016-01-11 17:10:00          60      30  19.89  46.693333   
2           2  2016-01-11 17:20:00          50      30  19.89  46.300000   
3           3  2016-01-11 17:30:00          50      40  19.89  46.066667   
4           4  2016-01-11 17:40:00          60      40  19.89  46.333333   

     T2       RH_2     T3       RH_3  ...         T9   RH_9     T_out  \
0  19.2  44.790000  19.79  44.730000  ...  17.033333  45.53  6.600000   
1  19.2  44.722500  19.79  44.790000  ...  17.066667  45.56  6.483333   
2  19.2  44.626667  19.79  44.933333  ...  17.000000  45.50  6.366667   
3  19.2  44.590000  19.79  45.000000  ...  17.000000  45.40  6.250000   
4  19.2  44.530000  19.79  45.000000  ...  17.000000  45.40  6.133333   

   Press_mm_hg  RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0        733.5    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1        733.6    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2        733.7    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3        733.8    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4        733.9    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 30 columns]

In [4]:
df.describe()

Unnamed: 0    Appliances        lights            T1          RH_1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean    9867.000000     97.694958      3.801875     21.686571     40.259739   
std     5697.148117    102.524891      7.935988      1.606066      3.979299   
min        0.000000     10.000000      0.000000     16.790000     27.023333   
25%     4933.500000     50.000000      0.000000     20.760000     37.333333   
50%     9867.000000     60.000000      0.000000     21.600000     39.656667   
75%    14800.500000    100.000000      0.000000     22.600000     43.066667   
max    19734.000000   1080.000000     70.000000     26.260000     63.360000   

                 T2          RH_2            T3          RH_3            T4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      20.341219     40.420420     22.267611     39.242500     20.855335   
std        2.192974      4.069813      2.006111      3.254576      2.042884   
min       16.100000     20.463333     17.200000     28.766667     15.100000   
25%       18.790000     37.900000     20.790000     36.900000     19.530000   
50%       20.000000     40.500000     22.100000     38.530000     20.666667   
75%       21.500000     43.260000     23.290000     41.760000     22.100000   
max       29.856667     56.026667     29.236000     50.163333     26.200000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 29 columns]

In [5]:
df1 = df.drop(columns=['date','lights'])
df1.head()

Unnamed: 0  Appliances     T1       RH_1    T2       RH_2     T3  \
0           0          60  19.89  47.596667  19.2  44.790000  19.79   
1           1          60  19.89  46.693333  19.2  44.722500  19.79   
2           2          50  19.89  46.300000  19.2  44.626667  19.79   
3           3          50  19.89  46.066667  19.2  44.590000  19.79   
4           4          60  19.89  46.333333  19.2  44.530000  19.79   

        RH_3         T4       RH_4  ...         T9   RH_9     T_out  \
0  44.730000  19.000000  45.566667  ...  17.033333  45.53  6.600000   
1  44.790000  19.000000  45.992500  ...  17.066667  45.56  6.483333   
2  44.933333  18.926667  45.890000  ...  17.000000  45.50  6.366667   
3  45.000000  18.890000  45.723333  ...  17.000000  45.40  6.250000   
4  45.000000  18.890000  45.530000  ...  17.000000  45.40  6.133333   

   Press_mm_hg  RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0        733.5    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1        733.6    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2        733.7    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3        733.8    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4        733.9    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 28 columns]

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_df1 = pd.DataFrame(scaler.fit_transform(df1), columns=df1.columns)
features_df1 = normalised_df1.drop(columns=['Appliances'])
target_Appliances = normalised_df1['Appliances']

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(features_df1, target_Appliances, test_size=0.3, random_state=42)



In [8]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)
predicted_values = linear_model.predict(x_test)
predicted_values

array([0.0341977 , 0.23166042, 0.03982327, ..., 0.07073048, 0.10464369,
       0.05450133])

In [9]:
linear_model.coef_

array([-0.07013016, -0.01721843,  0.55167625, -0.24394682, -0.45178088,
        0.3171688 ,  0.07456889,  0.02851846,  0.0184708 , -0.01334058,
        0.0143515 ,  0.22100784,  0.00939523,  0.00246276, -0.04165058,
        0.1016002 , -0.14668191, -0.14494027, -0.05821063, -0.25132948,
        0.01017101, -0.03295633,  0.0246724 ,  0.01149723,  0.09896923,
        0.00083106,  0.00083106])

In [10]:
#MAE
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 3)

0.05

In [11]:
#R_2
from sklearn.metrics import r2_score
r2_score1 = r2_score(y_test, predicted_values)
round(r2_score1, 2)

0.15

In [12]:
#RSS
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 3)

45.344

In [13]:
#RMSE
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
rmse

0.08751112322815924

In [14]:
#lasso Regression,  
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)
pred_lasso = lasso_reg.predict(x_test)

Lasso_rmse = np.sqrt(mean_squared_error(y_test, pred_lasso))
lasso_r2_score = r2_score(y_test, pred_lasso)
lasso_mae = mean_absolute_error(y_test, pred_lasso)


print(round(Lasso_rmse,3))
print(lasso_r2_score)
print (lasso_mae)
print(lasso_reg.coef_)

0.094
0.028320375246771556
0.05515645207566381
[-0.00448662  0.          0.02006354  0.00049124 -0.          0.
  0.          0.          0.         -0.          0.          0.
 -0.         -0.         -0.          0.         -0.00162075 -0.
 -0.          0.         -0.         -0.05157819  0.00062894  0.
  0.         -0.         -0.        ]


In [15]:
#Ridge Regression
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [16]:
pred_ridge =ridge_reg.predict(x_test)

ridge_rmse = np.sqrt(mean_squared_error(y_test, pred_ridge))
ridge_r2_score = r2_score(y_test, pred_ridge)
ridge_mae = mean_absolute_error(y_test, pred_ridge)
print(ridge_rmse)
print(ridge_r2_score)
print(ridge_mae)
print(ridge_reg.coef_)

0.08753180440683687
0.1485648685892338
0.05018275584568138
[-0.07131699 -0.03195776  0.51724939 -0.21004968 -0.40674547  0.31490827
  0.07358501  0.02695975  0.0162504  -0.01677182  0.01434769  0.20429883
  0.00690749  0.00260068 -0.04323272  0.10060068 -0.14546334 -0.14399311
 -0.05985018 -0.20346769  0.00990251 -0.01520178  0.02543558  0.01129768
  0.07223547  0.00081214  0.00081214]


In [18]:
def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_model_weights = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_Weight')
final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

final_weights

Features  Linear_Model_Weight  Ridge_Weight  Lasso_Weight
0          RH_2            -0.451781     -0.406745     -0.000000
1         T_out            -0.251329     -0.203468      0.000000
2            T2            -0.243947     -0.210050      0.000491
3          RH_8            -0.146682     -0.145463     -0.001621
4            T9            -0.144940     -0.143993     -0.000000
5    Unnamed: 0            -0.070130     -0.071317     -0.004487
6          RH_9            -0.058211     -0.059850     -0.000000
7          RH_7            -0.041651     -0.043233     -0.000000
8        RH_out            -0.032956     -0.015202     -0.051578
9            T1            -0.017218     -0.031958      0.000000
10           T5            -0.013341     -0.016772     -0.000000
11          rv1             0.000831      0.000812     -0.000000
12          rv2             0.000831      0.000812     -0.000000
13           T7             0.002463      0.002601     -0.000000
14         RH_6             0.009395      0.006907     -0.000000
15  Press_mm_hg             0.010171      0.009903     -0.000000
16   Visibility             0.011497      0.011298      0.000000
17         RH_5             0.014352      0.014348      0.000000
18         RH_4             0.018471      0.016250      0.000000
19    Windspeed             0.024672      0.025436      0.000629
20           T4             0.028518      0.026960      0.000000
21         RH_3             0.074569      0.073585      0.000000
22    Tdewpoint             0.098969      0.072235      0.000000
23           T8             0.101600      0.100601      0.000000
24           T6             0.221008      0.204299      0.000000
25           T3             0.317169      0.314908      0.000000
26         RH_1             0.551676      0.517249      0.020064

In [20]:
feature_T2 = normalised_df1['T2']
target_T6 = normalised_df1['T6']

array = np.array([feature_T2])
feature_T2 = array.reshape(-1,1)

x_train, x_test, y_train, y_test = train_test_split(feature_T2, target_T6, test_size=0.3, random_state=42)

linear_model_2 = LinearRegression()
linear_model_2.fit(x_train, y_train)
predicted_values_y = linear_model_2.predict(x_test)
predicted_values_y


array([0.23928945, 0.46794238, 0.23108472, ..., 0.3001772 , 0.4297256 ,
       0.3217686 ])

In [21]:
r2_score_T2 = r2_score(y_test, predicted_values_y)
round(r2_score_T2, 2)

0.64